### ISSUE TITLE
Moving left for the first action causes error

### ISSUE THREAD

**Issue by GDWR** [SavagePastaMan/pyweek-2021#48]
Moving left as the first action causes this error

```Traceback (most recent call last):
  File "C:\Users\nkrxh\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nkrxh\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\pyweek-2021\game\__main__.py", line 210, in <module>
    main()
  File "H:\pyweek-2021\game\__main__.py", line 206, in main
    arcade.run()
  File "H:\pyweek-2021\venv\lib\site-packages\arcade\window_commands.py", line 273, in run
    pyglet.app.run()
  File "H:\pyweek-2021\venv\lib\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "H:\pyweek-2021\venv\lib\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "H:\pyweek-2021\venv\lib\site-packages\pyglet\app\base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "H:\pyweek-2021\venv\lib\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "H:\pyweek-2021\game\__main__.py", line 138, in enemy_moving
    enemy.move_one()
  File "H:\pyweek-2021\game\entity\enemy.py", line 85, in move_one
    if self.movesleft > 0:
AttributeError: 'Enemy' object has no attribute 'movesleft'

Process finished with exit code 1
```

**Comment by SavagePastaMan** [comment]
we'll just never put the player next to a wall to start
